language: php
php:
  - 5.5

sudo: false

env:
  global:
    - SIMPLETEST_DB=sqlite://tmp/site.sqlite
    - SIMPLETEST_BASE_URL="http://127.0.0.1:8080"
  matrix:
    - RELEASE=stable

before_install:
  - echo 'sendmail_path = /bin/true' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - phpenv config-rm xdebug.ini
  - composer --verbose self-update
  - composer --version

install:
  - composer --verbose install

script:
  - if [[ $RELEASE = dev ]]; then composer --verbose require --no-update drupal/core:8.0.x-dev; fi;
  - if [[ $RELEASE = dev ]]; then composer --verbose update; fi;
  - cd $TRAVIS_BUILD_DIR/web
  - ./../vendor/bin/drush site-install --verbose --yes --db-url=sqlite://tmp/site.sqlite
  - ./../vendor/bin/drush runserver http://127.0.0.1:8080 &
  - sleep 3
  - ./../vendor/bin/drush sql-dump > clean-install.sql
  - ./../vendor/bin/drush en -y bootstrap
  - ./../vendor/bin/drush cex -y
  - ./../vendor/bin/drush sql-cli -y < clean-install.sql
  - ./../vendor/bin/drush cim -y
